import resend
import logging
from django.conf import settings

logger = logging.getLogger(__name__)

# Initialize Resend
if settings.RESEND_API_KEY:
    resend.api_key = settings.RESEND_API_KEY



def send_verification_email(user, otp):
    """
    Sends a verification OTP to the user.
    """
    if not settings.RESEND_API_KEY:
        logger.warning("Resend API key not configured. Skipping email.")
        return

    try:
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>Verify your Email</h2>
            <p>Hello {user.username},</p>
            <p>Your Luscent verification code is:</p>
            
            <div style="text-align: center; margin: 30px 0;">
                <span style="background-color: #f3f4f6; padding: 12px 24px; font-size: 24px; letter-spacing: 5px; font-weight: bold; border-radius: 4px;">{otp}</span>
            </div>
            
            <p style="color: #666; font-size: 14px;">This code will expire shortly.</p>
        </div>
        """

        params = {
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": "Your Verification Code",
            "html": html_content,
        }

        resend.Emails.send(params)
        logger.info(f"OTP sent to {user.email}")
        
    except Exception as e:
        logger.error(f"Failed to send verification email: {e}")



def send_password_reset_email(user, otp):
    """
    Sends a password reset OTP to the user.
    """
    if not settings.RESEND_API_KEY:
        logger.warning("Resend API key not configured. Skipping email.")
        return

    try:
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>Reset your Password</h2>
            <p>Hello {user.username},</p>
            <p>Your password reset code is:</p>
            
            <div style="text-align: center; margin: 30px 0;">
                <span style="background-color: #f3f4f6; padding: 12px 24px; font-size: 24px; letter-spacing: 5px; font-weight: bold; border-radius: 4px;">{otp}</span>
            </div>
            
            <p style="color: #666; font-size: 14px;">This code will expire shortly. If you did not request a password reset, please ignore this email.</p>
        </div>
        """

        params = {
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": "Password Reset Code",
            "html": html_content,
        }

        resend.Emails.send(params)
        logger.info(f"Password reset OTP sent to {user.email}")
        
    except Exception as e:
        logger.error(f"Failed to send password reset email: {e}")



def send_test_run_report(test_run):
    """
    Sends an email report for a completed test run.
    """
    if not settings.RESEND_API_KEY:
        logger.warning("Resend API key not configured. Skipping email.")
        return


    
    try:
        user = test_run.test_case.endpoint.collection.project.user
        test_case = test_run.test_case
        
        status_color = "#22c55e" if test_run.status == "passed" else "#ef4444"
        status_text = test_run.status.upper()
        
        # Simple HTML Template
        html_content = f"""
        <div style="font-family: ubuntu; max-width: 600px; margin: 0 auto;">
            <div style="background-color: #000; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                <h1 style="color: #000; margin: 0;">Luscent Test Report</h1>
            </div>
            <div style="padding: 20px; border: 1px solid #e5e7eb; border-radius: 0 0 8px 8px;">
                <p>Hello {user.username or 'there'},</p>
                <p>Your test case <strong>{test_case.name}</strong> has finished execution.</p>
                
                <div style="background-color: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
                    <p style="margin: 5px 0;"><strong>Status:</strong> <span style="color: {status_color}; font-weight: bold;">{status_text}</span></p>
                    <p style="margin: 5px 0;"><strong>Duration:</strong> {test_run.response_time_ms} ms</p>
                    <p style="margin: 5px 0;"><strong>Response Code:</strong> {test_run.response_status or 'N/A'}</p>
                </div>
                
                <h3>Details</h3>
                <pre style="background: #1f2937; color: #f9fafb; padding: 15px; border-radius: 5px; overflow-x: auto; font-size: 13px;">
{test_run.error_message if test_run.error_message else "No errors found."}
                </pre>
                
                <p style="margin-top: 30px; font-size: 12px; color: #6b7280; text-align: center;">
                    Generated by Luscent Sandbox Runner
                </p>
            </div>
        </div>
        """

        params = {
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": f"[{status_text}] Test Run: {test_case.name}",
            "html": html_content,
        }

        resend.Emails.send(params)
        logger.info(f"Report sent to {user.email}")
        
    except Exception as e:
        logger.error(f"Failed to send email notification: {e}")


def send_batch_report(batch_id, user):
    """
    Sends an aggregated report for all tests in a batch.
    """
    from test_cases.models import TestRun
    runs = TestRun.objects.filter(batch_id=batch_id)
    if not runs.exists():
        return

    total = runs.count()
    passed = runs.filter(status="passed").count()
    failed = runs.filter(status__in=["failed", "error"]).count()
    
    # Identify if it was an AI mission
    first_run = runs.first()
    is_ai_agent = first_run.triggered_by == "ai_agent"
    test_case = first_run.test_case
    user_story = test_case.user_story if is_ai_agent else None
    
    # Extract Metadata
    category = test_case.category.upper() if test_case.category else "FUNCTIONAL"
    layer = test_case.layer.upper() if test_case.layer else "BACKEND"
    tags = test_case.tags if test_case.tags else []
    scenarios = ", ".join([t.replace("SCENARIO:", "") for t in tags if t.startswith("SCENARIO:")])
    
    is_scheduled = runs.filter(triggered_by="scheduled").exists()
    title = "AI Mission Execution Report" if is_ai_agent else ("Scheduled Uptime Report" if is_scheduled else "Batch Execution Report")

    # Build Metadata Bar
    metadata_bar = f"""
    <div style="display: flex; gap: 10px; margin-bottom: 20px; font-size: 11px; font-weight: bold; color: #718096; text-transform: uppercase;">
        <span style="background: #edf2f7; padding: 4px 8px; border-radius: 4px;">📂 {category}</span>
        <span style="background: #edf2f7; padding: 4px 8px; border-radius: 4px;">💻 {layer}</span>
        {f'<span style="background: #edf2f7; padding: 4px 8px; border-radius: 4px;">🎯 {scenarios}</span>' if scenarios else ''}
    </div>
    """

    # Build summarized table
    rows = ""
    for run in runs:
        s_color = "#22c55e" if run.status == "passed" else "#ef4444"
        # Extract AI Thought if present (stored prefix in logs)
        ai_thought = ""
        if is_ai_agent and run.logs:
             thought_line = [l for l in run.logs.split("\n") if l.startswith("AI THOUGHT:")]
             if thought_line:
                 ai_thought = thought_line[0].replace("AI THOUGHT:", "").strip()
        
        detail_desc = run.test_case.description if is_ai_agent else f"Code: {run.response_status or 'N/A'}"
        
        rows += f"""
        <tr style="border-bottom: 1px solid #edf2f7;">
            <td style="padding: 16px 12px; vertical-align: top;">
                <div style="font-weight: 600; color: #2d3748;">{run.test_case.name}</div>
                <div style="font-size: 11px; font-family: monospace; color: #4a5568; margin-top: 4px; background: #f1f5f9; padding: 2px 6px; border-radius: 4px; display: inline-block;">
                    {run.test_case.endpoint.method if run.test_case.endpoint else 'AI'} {run.test_case.endpoint.url if run.test_case.endpoint else 'Dynamic Path'}
                </div>
                <div style="font-size: 12px; color: #718096; margin-top: 8px; line-height: 1.4;">{ai_thought or detail_desc}</div>
                {f'<div style="font-size: 11px; color: #e53e3e; margin-top: 8px; background: #fff5f5; padding: 8px; border: 1px solid #feb7b7; border-radius: 4px; font-family: monospace;"><strong>Error:</strong> {run.response_body if isinstance(run.response_body, str) else json.dumps(run.response_body)[:200]}</div>' if run.status != 'passed' else ''}
            </td>
            <td style="padding: 16px 12px; vertical-align: top; text-align: center;">
                <span style="background-color: {s_color}15; color: {s_color}; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; text-transform: uppercase;">
                    {run.status}
                </span>
            </td>
            <td style="padding: 16px 12px; vertical-align: top; text-align: right; color: #718096; font-size: 13px;">
                {run.response_time_ms}ms
            </td>
        </tr>
        """

    story_section = f"""
    <div style="background-color: #f7fafc; border-left: 4px solid #4a5568; padding: 16px; margin-bottom: 24px; border-radius: 0 4px 4px 0;">
        <div style="font-size: 12px; font-weight: bold; color: #4a5568; text-transform: uppercase; margin-bottom: 4px;">Verified User Story</div>
        <div style="color: #2d3748; font-style: italic; line-height: 1.5;">"{user_story}"</div>
    </div>
    """ if user_story else ""

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #2d3748; margin: 0; padding: 0; }}
        </style>
    </head>
    <body style="background-color: #f4f7f9; padding: 20px;">
        <div style="max-width: 650px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
            <!-- Header -->
            <div style="background: linear-gradient(135deg, #1a202c 0%, #2d3748 100%); padding: 32px 24px; text-align: center;">
                <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.025em;">Luscent Mission Control</h1>
                <p style="color: #a0aec0; margin: 8px 0 0 0; font-size: 14px;">{title}</p>
            </div>
            
            <div style="padding: 32px 24px;">
                {story_section}
                {metadata_bar}
                
                <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 32px; text-align: center;">
                    <div style="background-color: #f8fafc; padding: 16px; border-radius: 8px; border: 1px solid #edf2f7;">
                        <div style="font-size: 24px; font-weight: 800; color: #2d3748;">{total}</div>
                        <div style="font-size: 11px; font-weight: bold; color: #718096; text-transform: uppercase;">Total Steps</div>
                    </div>
                    <div style="background-color: #f0fff4; padding: 16px; border-radius: 8px; border: 1px solid #c6f6d5;">
                        <div style="font-size: 24px; font-weight: 800; color: #38a169;">{passed}</div>
                        <div style="font-size: 11px; font-weight: bold; color: #38a169; text-transform: uppercase;">Passed</div>
                    </div>
                    <div style="background-color: #fff5f5; padding: 16px; border-radius: 8px; border: 1px solid #fed7d7;">
                        <div style="font-size: 24px; font-weight: 800; color: #e53e3e;">{failed}</div>
                        <div style="font-size: 11px; font-weight: bold; color: #e53e3e; text-transform: uppercase;">Failed</div>
                    </div>
                </div>

                <div style="margin-bottom: 24px;">
                    <h3 style="font-size: 16px; font-weight: 700; color: #2d3748; margin: 0 0 16px 0; padding-bottom: 8px; border-bottom: 2px solid #edf2f7;">
                        Test Execution Details
                    </h3>
                    <table style="width: 100%; border-collapse: collapse;">
                        <thead>
                            <tr style="text-align: left; font-size: 11px; font-weight: 700; color: #a0aec0; text-transform: uppercase; background-color: #f8fafc;">
                                <th style="padding: 12px;">Step & Methodology</th>
                                <th style="padding: 12px; text-align: center;">Status</th>
                                <th style="padding: 12px; text-align: right;">Latency</th>
                            </tr>
                        </thead>
                        <tbody>
                            {rows}
                        </tbody>
                    </table>
                </div>

                <!-- Footer -->
                <div style="margin-top: 40px; padding-top: 24px; border-top: 1px solid #edf2f7; text-align: center;">
                    <p style="font-size: 14px; color: #4a5568; margin-bottom: 8px;">
                        The mission resulted in a <strong>{int(passed/total*100) if total > 0 else 0}%</strong> success rate.
                    </p>
                    <p style="font-size: 12px; color: #a0aec0;">
                        Batch ID: {batch_id} <br>
                        Sent via Luscent Autonomous Engine • {runs.first().executed_at.strftime('%Y-%m-%d %H:%M:%S UTC')}
                    </p>
                </div>
            </div>
        </div>
    </body>
    </html>
    """

    try:
        resend.Emails.send({
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": f"[{passed}/{total} Passed] {title}",
            "html": html_content
        })
        logger.info(f"Batch report sent to {user.email}")
    except Exception as e:
        logger.error(f"Failed to send batch report: {e}")


