import resend
import logging
from django.conf import settings

logger = logging.getLogger(__name__)

# Initialize Resend
if settings.RESEND_API_KEY:
    resend.api_key = settings.RESEND_API_KEY



def send_verification_email(user, otp):
    """
    Sends a verification OTP to the user.
    """
    if not settings.RESEND_API_KEY:
        logger.warning("Resend API key not configured. Skipping email.")
        return

    try:
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>Verify your Email</h2>
            <p>Hello {user.username},</p>
            <p>Your Luscent verification code is:</p>
            
            <div style="text-align: center; margin: 30px 0;">
                <span style="background-color: #f3f4f6; padding: 12px 24px; font-size: 24px; letter-spacing: 5px; font-weight: bold; border-radius: 4px;">{otp}</span>
            </div>
            
            <p style="color: #666; font-size: 14px;">This code will expire shortly.</p>
        </div>
        """

        params = {
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": "Your Verification Code",
            "html": html_content,
        }

        resend.Emails.send(params)
        logger.info(f"OTP sent to {user.email}")
        
    except Exception as e:
        logger.error(f"Failed to send verification email: {e}")



def send_password_reset_email(user, otp):
    """
    Sends a password reset OTP to the user.
    """
    if not settings.RESEND_API_KEY:
        logger.warning("Resend API key not configured. Skipping email.")
        return

    try:
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>Reset your Password</h2>
            <p>Hello {user.username},</p>
            <p>Your password reset code is:</p>
            
            <div style="text-align: center; margin: 30px 0;">
                <span style="background-color: #f3f4f6; padding: 12px 24px; font-size: 24px; letter-spacing: 5px; font-weight: bold; border-radius: 4px;">{otp}</span>
            </div>
            
            <p style="color: #666; font-size: 14px;">This code will expire shortly. If you did not request a password reset, please ignore this email.</p>
        </div>
        """

        params = {
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": "Password Reset Code",
            "html": html_content,
        }

        resend.Emails.send(params)
        logger.info(f"Password reset OTP sent to {user.email}")
        
    except Exception as e:
        logger.error(f"Failed to send password reset email: {e}")



def send_test_run_report(test_run):
    """
    Sends an email report for a completed test run.
    """
    if not settings.RESEND_API_KEY:
        logger.warning("Resend API key not configured. Skipping email.")
        return


    
    try:
        user = test_run.test_case.endpoint.collection.project.user
        test_case = test_run.test_case
        
        status_color = "#22c55e" if test_run.status == "passed" else "#ef4444"
        status_text = test_run.status.upper()
        
        # Simple HTML Template
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background-color: #000; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                <h1 style="color: #fff; margin: 0;">QAi Test Report</h1>
            </div>
            <div style="padding: 20px; border: 1px solid #e5e7eb; border-radius: 0 0 8px 8px;">
                <p>Hello {user.username or 'there'},</p>
                <p>Your test case <strong>{test_case.name}</strong> has finished execution.</p>
                
                <div style="background-color: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
                    <p style="margin: 5px 0;"><strong>Status:</strong> <span style="color: {status_color}; font-weight: bold;">{status_text}</span></p>
                    <p style="margin: 5px 0;"><strong>Duration:</strong> {test_run.response_time_ms} ms</p>
                    <p style="margin: 5px 0;"><strong>Response Code:</strong> {test_run.response_status or 'N/A'}</p>
                </div>
                
                <h3>Details</h3>
                <pre style="background: #1f2937; color: #f9fafb; padding: 15px; border-radius: 5px; overflow-x: auto; font-size: 13px;">
{test_run.error_message if test_run.error_message else "No errors found."}
                </pre>
                
                <p style="margin-top: 30px; font-size: 12px; color: #6b7280; text-align: center;">
                    Generated by QAi Sandbox Runner
                </p>
            </div>
        </div>
        """

        params = {
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": f"[{status_text}] Test Run: {test_case.name}",
            "html": html_content,
        }

        resend.Emails.send(params)
        logger.info(f"Report sent to {user.email}")
        
    except Exception as e:
        logger.error(f"Failed to send email notification: {e}")


def send_batch_report(batch_id, user):
    """
    Sends an aggregated report for all tests in a batch.
    """
    from test_cases.models import TestRun
    runs = TestRun.objects.filter(batch_id=batch_id)
    if not runs.exists():
        return

    total = runs.count()
    passed = runs.filter(status="passed").count()
    failed = runs.filter(status__in=["failed", "error"]).count()
    
    # Identify if it was a scheduled check
    is_scheduled = runs.filter(triggered_by="scheduled").exists()
    title = "Scheduled Uptime Report" if is_scheduled else "Batch Execution Report"

    # Build summarized table
    rows = ""
    for run in runs:
        s_color = "#22c55e" if run.status == "passed" else "#ef4444"
        rows += f"""
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">{run.test_case.name}</td>
            <td style="padding: 10px; border-bottom: 1px solid #eee; color: {s_color}; font-weight: bold;">{run.status.upper()}</td>
            <td style="padding: 10px; border-bottom: 1px solid #eee;">{run.response_time_ms}ms</td>
        </tr>
        """

    html_content = f"""
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px;">
        <div style="background-color: #111; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
            <h2 style="color: #fff; margin: 0;">{title}</h2>
        </div>
        <div style="padding: 20px;">
            <p>Summary for Batch: <code style="background: #f3f4f6; padding: 2px 4px;">{batch_id}</code></p>
            
            <div style="display: flex; justify-content: space-around; background: #f9fafb; padding: 15px; border-radius: 8px; margin-bottom: 20px; text-align: center;">
                <div><div style="font-size: 20px; font-weight: bold;">{total}</div><div style="font-size: 12px; color: #666;">Total</div></div>
                <div><div style="font-size: 20px; font-weight: bold; color: #22c55e;">{passed}</div><div style="font-size: 12px; color: #666;">Passed</div></div>
                <div><div style="font-size: 20px; font-weight: bold; color: #ef4444;">{failed}</div><div style="font-size: 12px; color: #666;">Failed</div></div>
            </div>

            <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
                <thead>
                    <tr style="background: #f3f4f6;">
                        <th style="text-align: left; padding: 10px;">Test Case</th>
                        <th style="text-align: left; padding: 10px;">Status</th>
                        <th style="text-align: left; padding: 10px;">Duration</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>

            <p style="margin-top: 30px; font-size: 12px; color: #999; text-align: center;">
                This is an aggregated report to reduce email frequency.
            </p>
        </div>
    </div>
    """

    try:
        resend.Emails.send({
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": f"[{passed}/{total} Passed] {title}",
            "html": html_content
        })
        logger.info(f"Batch report sent to {user.email}")
    except Exception as e:
        logger.error(f"Failed to send batch report: {e}")


