import resend
import logging
from django.conf import settings

logger = logging.getLogger(__name__)

# Initialize Resend
if settings.RESEND_API_KEY:
    resend.api_key = settings.RESEND_API_KEY



def send_verification_email(user, otp):
    """
    Sends a verification OTP to the user.
    """
    if not settings.RESEND_API_KEY:
        logger.warning("Resend API key not configured. Skipping email.")
        return

    try:
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>Verify your Email</h2>
            <p>Hello {user.username},</p>
            <p>Your Luscent verification code is:</p>
            
            <div style="text-align: center; margin: 30px 0;">
                <span style="background-color: #f3f4f6; padding: 12px 24px; font-size: 24px; letter-spacing: 5px; font-weight: bold; border-radius: 4px;">{otp}</span>
            </div>
            
            <p style="color: #666; font-size: 14px;">This code will expire shortly.</p>
        </div>
        """

        params = {
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": "Your Verification Code",
            "html": html_content,
        }

        resend.Emails.send(params)
        logger.info(f"OTP sent to {user.email}")
        
    except Exception as e:
        logger.error(f"Failed to send verification email: {e}")



def send_password_reset_email(user, otp):
    """
    Sends a password reset OTP to the user.
    """
    if not settings.RESEND_API_KEY:
        logger.warning("Resend API key not configured. Skipping email.")
        return

    try:
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>Reset your Password</h2>
            <p>Hello {user.username},</p>
            <p>Your password reset code is:</p>
            
            <div style="text-align: center; margin: 30px 0;">
                <span style="background-color: #f3f4f6; padding: 12px 24px; font-size: 24px; letter-spacing: 5px; font-weight: bold; border-radius: 4px;">{otp}</span>
            </div>
            
            <p style="color: #666; font-size: 14px;">This code will expire shortly. If you did not request a password reset, please ignore this email.</p>
        </div>
        """

        params = {
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": "Password Reset Code",
            "html": html_content,
        }

        resend.Emails.send(params)
        logger.info(f"Password reset OTP sent to {user.email}")
        
    except Exception as e:
        logger.error(f"Failed to send password reset email: {e}")



def send_test_run_report(test_run):
    """
    Sends an email report for a completed test run.
    """
    if not settings.RESEND_API_KEY:
        logger.warning("Resend API key not configured. Skipping email.")
        return

    try:
        user = test_run.test_case.collection.project.user
        test_case = test_run.test_case
        
        status_color = "#22c55e" if test_run.status == "passed" else "#ef4444"
        status_text = test_run.status.upper()
        
        # Simple HTML Template
        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>Test Run Report</h2>
            <p>Hello {user.username},</p>
            <p>Your test case <strong>{test_case.name}</strong> has finished execution.</p>
            
            <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <p><strong>Status:</strong> <span style="color: {status_color}; font-weight: bold;">{status_text}</span></p>
                <p><strong>Duration:</strong> {test_run.response_time_ms} ms</p>
                <p><strong>Response Code:</strong> {test_run.response_status}</p>
            </div>
            
            <h3>Details</h3>
            <pre style="background: #111; color: #fff; padding: 15px; border-radius: 5px; overflow-x: auto;">
{test_run.error_message if test_run.error_message else "No errors found."}
            </pre>
            
            <p style="margin-top: 30px; font-size: 12px; color: #666;">
                Generated by Luscent
            </p>
        </div>
        """

        params = {
            "from": settings.DEFAULT_FROM_EMAIL,
            "to": [user.email],
            "subject": f"[{status_text}] Test Run: {test_case.name}",
            "html": html_content,
        }

        email = resend.Emails.send(params)
        logger.info(f"Email sent to {user.email}: {email}")
        
    except Exception as e:
        logger.error(f"Failed to send email notification: {e}")


