# Generated by Django 6.0 on 2026-01-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('expected_status', models.IntegerField(default=200)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('runner_type', models.CharField(choices=[('http', 'HTTP Request'), ('browser', 'Browser (Playwright)'), ('load', 'Load Test (Locust)')], default='http', max_length=20)),
                ('test_script', models.TextField(blank=True, help_text='AI-generated python/js script for execution', null=True)),
                ('use_visual_ai', models.BooleanField(default=False, help_text='If true, takes screenshot and analyzes with AI')),
                ('category', models.CharField(choices=[('functional', 'Functional'), ('smoke', 'Smoke'), ('regression', 'Regression'), ('security', 'Security'), ('performance', 'Performance'), ('e2e', 'End-to-End')], default='functional', max_length=20)),
                ('layer', models.CharField(choices=[('backend', 'Backend (API)'), ('frontend', 'Frontend (UI)')], default='backend', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text="e.g. ['SCENARIO:HAPPY_PATH', 'CRITICAL']")),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='collection.collection')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('screenshot_url', models.URLField(blank=True, help_text='Cloudinary URL', max_length=500, null=True)),
                ('screenshot_public_id', models.CharField(blank=True, help_text='Cloudinary public ID for deletion', max_length=255, null=True)),
                ('screenshot_size_bytes', models.IntegerField(default=0, help_text='File size for quota tracking')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='test_cases.testcase')),
            ],
        ),
    ]
