# Generated by Django 6.0 on 2026-01-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='user_story',
            field=models.TextField(blank=True, help_text='User story/requirements context used to generate this test', null=True),
        ),
    ]
