# Generated by Django 6.0 on 2026-01-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0002_testcase_user_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Group ID for batch executions', null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='triggered_by',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI Auto-Pilot'), ('webhook', 'Webhook')], default='manual', max_length=50),
        ),
    ]
