# Generated by Django 6.0 on 2025-12-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0002_testrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='category',
            field=models.CharField(choices=[('functional', 'Functional'), ('smoke', 'Smoke'), ('regression', 'Regression'), ('security', 'Security'), ('performance', 'Performance'), ('e2e', 'End-to-End')], default='functional', max_length=20),
        ),
        migrations.AddField(
            model_name='testcase',
            name='layer',
            field=models.CharField(choices=[('backend', 'Backend (API)'), ('frontend', 'Frontend (UI)')], default='backend', max_length=20),
        ),
        migrations.AddField(
            model_name='testcase',
            name='runner_type',
            field=models.CharField(choices=[('http', 'HTTP Request'), ('browser', 'Browser (Playwright)'), ('load', 'Load Test (Locust)')], default='http', max_length=20),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_script',
            field=models.TextField(blank=True, help_text='AI-generated python/js script for execution', null=True),
        ),
    ]
