# Generated by Django 6.0 on 2025-12-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0003_testcase_category_testcase_layer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['SCENARIO:HAPPY_PATH', 'CRITICAL']"),
        ),
    ]
