# Generated by Django 6.0.1 on 2026-02-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0004_rename_testcase_collection_to_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='triggered_by',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI Auto-Pilot'), ('webhook', 'Webhook'), ('scheduled', 'Scheduled')], default='manual', max_length=50),
        ),
    ]
