# Generated by Django 6.0 on 2025-12-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0004_testcase_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
