# Generated by Django 6.0.1 on 2026-02-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('remote_runners', '0001_initial'),
        ('test_cases', '0005_alter_testrun_triggered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='assigned_runner',
            field=models.ForeignKey(blank=True, help_text='The remote runner assigned to execute this test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_runs', to='remote_runners.remoterunner'),
        ),
    ]
