# Generated by Django 6.0 on 2025-12-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0005_alter_testcase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='use_visual_ai',
            field=models.BooleanField(default=False, help_text='If true, takes screenshot and analyzes with AI'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='test_screenshots/'),
        ),
    ]
