# Generated by Django 6.0 on 2025-12-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0006_testcase_use_visual_ai_testrun_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='testrun',
            name='screenshot_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for deletion', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='screenshot_size_bytes',
            field=models.IntegerField(default=0, help_text='File size for quota tracking'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='screenshot_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL', max_length=500, null=True),
        ),
    ]
