# Generated by Django 6.0.1 on 2026-02-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0006_testrun_assigned_runner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='assigned_runner',
        ),
    ]
