# Generated by Django 6.0.1 on 2026-02-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0008_testrun_extracted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Variables extracted from this run for use in the batch', null=True),
        ),
    ]
