# Generated by Django 6.0.1 on 2026-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0009_alter_testrun_extracted_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='keep_alive',
            field=models.BooleanField(default=False, help_text='If true, the E2B sandbox will be kept alive for a period after execution'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='sandbox_id',
            field=models.CharField(blank=True, help_text='E2B Sandbox ID for session persistence', max_length=100, null=True),
        ),
    ]
