# Generated by Django 6.0.1 on 2026-02-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0011_agentmission_agentmissionstep_agentprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='browser_config',
            field=models.JSONField(blank=True, default=dict, help_text="Configs like: {'browser': 'firefox', 'device': 'iPhone 14', 'network': 'Slow_3G', 'geolocation': ...}"),
        ),
        migrations.AddField(
            model_name='testrun',
            name='browser_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config used: browser, device, network throttling'),
        ),
    ]
