# Generated by Django 6.0.1 on 2026-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0012_testcase_browser_config_testrun_browser_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmission',
            name='browser_config',
            field=models.JSONField(blank=True, default=dict, help_text="Configs like: {'browser': 'firefox', 'device': 'iPhone 14'}"),
        ),
    ]
