# Generated by Django 6.0.1 on 2026-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0013_agentmission_browser_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmission',
            name='session_url',
            field=models.URLField(blank=True, help_text='Public URL to the running Sandbox for manual testing', null=True),
        ),
    ]
