# Generated by Django 6.0.1 on 2026-02-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0014_agentmission_session_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmission',
            name='mission_type',
            field=models.CharField(choices=[('qa_testing', 'QA Feature Testing'), ('security_audit', 'Security Pentesting')], default='qa_testing', max_length=20),
        ),
    ]
