# Generated by Django 6.0.1 on 2026-02-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0015_agentmission_mission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmission',
            name='is_safe_mode',
            field=models.BooleanField(default=True, help_text='In Safe Mode, the agent avoids destructive actions (Delete, Update) on production URLs.'),
        ),
    ]
