# Generated by Django 6.0.1 on 2026-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0016_agentmission_is_safe_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmission',
            name='error_message',
            field=models.TextField(blank=True, help_text='Why the mission failed (billing, setup, etc.)', null=True),
        ),
    ]
