# Generated by Django 6.0.1 on 2026-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0017_agentmission_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmission',
            name='app_url',
            field=models.URLField(blank=True, help_text="Public URL to the user's app running inside the sandbox", null=True),
        ),
    ]
