# Generated by Django 6.0.1 on 2026-09-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0018_add_app_url_to_agent_mission'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['test_case', '-executed_at'], name='idx_run_tc_executed'),
        ),
    ]
