# Generated by Django 5.1.15 on 2026-09-01 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0019_add_testrun_executed_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmission',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the mission finished (passed/failed/error)', null=True),
        ),
        migrations.AddField(
            model_name='agentmission',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Total mission wall-clock duration in seconds'),
        ),
        migrations.AddField(
            model_name='agentmission',
            name='failed_steps',
            field=models.IntegerField(default=0, help_text='Steps that failed'),
        ),
        migrations.AddField(
            model_name='agentmission',
            name='passed_steps',
            field=models.IntegerField(default=0, help_text='Steps that passed'),
        ),
        migrations.AddField(
            model_name='agentmission',
            name='previous_session',
            field=models.ForeignKey(blank=True, help_text='Previous session this one is regressing against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regression_sessions', to='test_cases.agentmission'),
        ),
        migrations.AddField(
            model_name='agentmission',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated executive summary of the mission', null=True),
        ),
        migrations.AddField(
            model_name='agentmission',
            name='total_steps',
            field=models.IntegerField(default=0, help_text='Total steps executed in this mission'),
        ),
    ]
