# Generated by Django 5.1.15 on 2026-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0020_add_session_report_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmission',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Test categories: ["functional", "security", ...]'),
        ),
        migrations.AddField(
            model_name='agentmission',
            name='scenarios',
            field=models.JSONField(blank=True, default=list, help_text='User-selected scenarios: ["HAPPY_PATH", "SECURITY", ...]'),
        ),
    ]
