# Generated by Django 5.1.15 on 2026-09-10 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_fix_endpoint_id_type'),
        ('test_cases', '0021_add_mission_scenarios_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='collection.endpoint'),
        ),
    ]
