# Generated by Django 5.1.15 on 2026-09-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0018_agentmission_load_config'),
        ('test_cases', '0022_fix_endpoint_id_type'),
    ]

    operations = [
    ]
