# Generated by Django 6.0 on 2026-01-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_user_verification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test_runs_limit',
            new_name='token_balance',
        ),
    ]
