# Generated by Django 6.0 on 2026-01-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_test_runs_limit_user_token_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_balance',
        ),
    ]
