# Generated by Django 6.0.1 on 2026-02-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_github_token_user_github_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('email', 'Standard Email/Password'), ('other', 'Other')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(help_text='Stored as provided. Production should use encryption.', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra config like client_id, secret, or specific target domains')),
                ('description', models.TextField(blank=True, help_text='Context on where and why to use these credentials', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Agent Credential',
                'verbose_name_plural': 'Global Agent Credentials',
            },
        ),
    ]
