# Generated by Django 6.0 on 2026-01-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_token_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_balance',
            field=models.IntegerField(default=100),
        ),
    ]
