# Generated by Django 5.1.15 on 2026-09-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_target_url'),
        ('users', '0004_testcredential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcredential',
            options={'verbose_name': 'Agent Credential', 'verbose_name_plural': 'Agent Credentials'},
        ),
        migrations.AddField(
            model_name='testcredential',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this credential is scoped to. Empty = shared across projects (staff-managed).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_credentials', to='projects.project'),
        ),
    ]
