# Generated by Django 6.0 on 2026-01-06 13:20

import encrypted_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('environment_variables', encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict, help_text='Key-value pairs for test generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_used_bytes', models.BigIntegerField(default=0, help_text='Total storage used in bytes')),
                ('storage_quota_bytes', models.BigIntegerField(default=104857600, help_text='Storage quota in bytes (default: 100 MB)')),
            ],
        ),
    ]
