# Generated by Django 6.0 on 2025-12-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('backend', 'Backend API'), ('frontend', 'Frontend UI'), ('both', 'Full Stack')], default='backend', max_length=20)),
                ('api_url', models.URLField(blank=True, help_text='Base URL of the API')),
                ('swagger_url', models.URLField(blank=True, help_text='URL to OpenAPI/Swagger spec')),
                ('swagger_spec', models.JSONField(blank=True, help_text='Uploaded Swagger spec', null=True)),
                ('frontend_url', models.URLField(blank=True, help_text='URL of the frontend application')),
                ('enable_security_tests', models.BooleanField(default=True)),
                ('enable_performance_tests', models.BooleanField(default=False)),
                ('enable_a11y_tests', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
