# Generated by Django 6.0.1 on 2026-02-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
