# Generated by Django 6.0 on 2025-12-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('backend', 'Backend API'), ('frontend', 'Frontend UI'), ('full stack', 'Full Stack')], default='backend', max_length=20),
        ),
    ]
