# Generated by Django 6.0 on 2025-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='enable_a11y_tests',
        ),
        migrations.RemoveField(
            model_name='project',
            name='enable_performance_tests',
        ),
        migrations.RemoveField(
            model_name='project',
            name='enable_security_tests',
        ),
        migrations.RemoveField(
            model_name='project',
            name='frontend_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='swagger_spec',
        ),
        migrations.RemoveField(
            model_name='project',
            name='swagger_url',
        ),
        migrations.AddField(
            model_name='project',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Auth'), ('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='auth_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='base_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='default_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
