# Generated by Django 6.0.1 on 2026-02-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_user_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_branch',
            field=models.CharField(blank=True, default='main', help_text='Branch to clone', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_type',
            field=models.CharField(blank=True, help_text="e.g., 'frontend', 'backend', 'mobile', 'fullstack'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, help_text='GitHub/GitLab repository URL for white-box testing', null=True),
        ),
    ]
