# Generated by Django 6.0.1 on 2026-08-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_repo_branch_project_repo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('api_key', 'API Key'), ('session', 'Session/Cookie'), ('jwt', 'JWT'), ('oauth', 'OAuth'), ('custom', 'Custom')], default='none', help_text='Primary authentication mechanism', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='critical_flows',
            field=models.JSONField(blank=True, default=list, help_text='Prioritized user flows: [{"name": "Login", "priority": "P0", "description": "..."}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='domain_rules',
            field=models.TextField(blank=True, help_text='Business rules and domain constraints for the agent', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict, help_text='Structured tech stack: {"frontend": "React", "backend": "Django", "database": "Postgres"}'),
        ),
    ]
