# Generated by Django 6.0 on 2025-12-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_remove_project_api_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='auth_value',
        ),
        migrations.RemoveField(
            model_name='project',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='default_headers',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
