# Generated by Django 6.0.1 on 2026-08-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_structured_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='postman_collection',
            field=models.JSONField(blank=True, default=None, help_text='Parsed Postman collection JSON for auto-importing endpoints', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='swagger_url',
            field=models.URLField(blank=True, help_text='URL to OpenAPI/Swagger spec for auto-importing endpoints', null=True),
        ),
    ]
