# Generated by Django 6.0 on 2025-12-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_auth_type_remove_project_auth_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='base_url',
            field=models.URLField(blank=True, help_text='Default base URL for this project (e.g. http://localhost:8000)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='environment_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value pairs for test environment (e.g. valid_email, auth_token)'),
        ),
    ]
