# Generated by Django 6.0.1 on 2026-08-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_swagger_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preferred_test_types',
            field=models.JSONField(blank=True, default=list, help_text='Preferred test scenarios: ["HAPPY_PATH", "SECURITY", "VALIDATION_ERROR", "EDGE_CASE", "PERFORMANCE", "SMOKE", "REGRESSION", "E2E"]'),
        ),
    ]
