# Generated by Django 6.0 on 2025-12-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_base_url_project_environment_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='base_url',
        ),
        migrations.AlterField(
            model_name='project',
            name='environment_variables',
            field=models.JSONField(blank=True, default=dict, help_text="Key-value pairs for test generation (e.g. {'VALID_USER': 'admin'})"),
        ),
    ]
