# Generated by Django 6.0 on 2025-12-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='storage_quota_bytes',
            field=models.BigIntegerField(default=104857600, help_text='Storage quota in bytes (default: 100 MB)'),
        ),
        migrations.AddField(
            model_name='project',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0, help_text='Total storage used in bytes'),
        ),
    ]
