# Generated by Django 6.0.1 on 2026-08-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_preferred_test_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_url',
            field=models.URLField(blank=True, help_text='Primary target application URL for testing', null=True),
        ),
    ]
