# Generated by Django 6.0 on 2026-01-01 11:15

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_storage_quota_bytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='environment_variables',
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict, help_text='Key-value pairs for test generation'),
        ),
    ]
