# Generated by Django 6.0 on 2026-01-06 13:20

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('auth_type', models.CharField(choices=[('none', 'No Auth'), ('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth')], default='none', max_length=20)),
                ('auth_value', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True)),
                ('query_params', encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict)),
                ('headers', encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict)),
                ('request_body', encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('swagger', 'Swagger'), ('postman', 'Postman'), ('crawler', 'Crawler')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
