# Generated by Django 6.0 on 2025-12-10 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_alter_project_options_remove_project_api_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('swagger', 'Swagger'), ('postman', 'Postman'), ('crawler', 'Crawler')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'method', 'path')},
            },
        ),
    ]
