# Generated by Django 6.0 on 2026-01-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('project', 'method', 'url')},
        ),
    ]
