# Generated by Django 6.0 on 2025-12-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('projects', '0005_remove_project_auth_type_remove_project_auth_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='path',
            new_name='url',
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('project', 'method', 'url')},
        ),
        migrations.AddField(
            model_name='collection',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Auth'), ('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='collection',
            name='auth_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
