# Generated by Django 6.0 on 2026-01-01 11:15

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_path_collection_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='auth_value',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='headers',
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='collection',
            name='query_params',
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='collection',
            name='request_body',
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
    ]
