# Generated by Django 6.0.1 on 2026-02-01 00:25

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_rename_collection_to_endpoint'),
        ('projects', '0002_initial'),
    ]

    operations = [
        # Removed AlterUniqueTogether because it's causing issues after table rename
        migrations.AlterField(
            model_name='endpoint',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints_legacy', to='projects.project'),
        ),
        # Table is already named correctly or will be handled by default
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_url', models.CharField(blank=True, max_length=500, null=True)),
                ('headers', encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('swagger', 'Swagger'), ('postman', 'Postman'), ('crawler', 'Crawler')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.AddField(
            model_name='endpoint',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='collection.collection'),
        ),
    ]
