# Generated by Django 6.0.1 on 2026-02-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_endpoint_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endpoint',
            table=None,
        ),
    ]
