# Generated by Django 6.0.1 on 2026-02-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_endpoint_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='last_scheduled_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='schedule_interval',
            field=models.IntegerField(blank=True, choices=[(5, '5 Minutes'), (15, '15 Minutes'), (60, '1 Hour'), (1440, '24 Hours')], default=60, null=True),
        ),
    ]
