# Generated by Django 6.0.1 on 2026-02-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_collection_is_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
