# Generated by Django 6.0.1 on 2026-02-03 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_collection_user_story'),
        ('projects', '0002_initial'), # Ensure we know about Project model if needed, but not strictly required for this ID change
    ]

    operations = [
        # 1. Truncate to clear data (User accepted this implication)
        migrations.RunSQL(
            "TRUNCATE TABLE collection_collection CASCADE;", 
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # 2. Drop PK and Cascade to remove Foreign Keys from Endpoint etc.
        migrations.RunSQL(
            "ALTER TABLE collection_collection ALTER COLUMN id DROP IDENTITY IF EXISTS;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "ALTER TABLE collection_collection DROP CONSTRAINT collection_collection_pkey1 CASCADE;",
            reverse_sql=migrations.RunSQL.noop
        ),

        # 3. Change ID to UUID (Valid because table is empty)
        migrations.RunSQL(
            "ALTER TABLE collection_collection ALTER COLUMN id TYPE uuid USING gen_random_uuid();",
            reverse_sql=migrations.RunSQL.noop
        ),

        # 4. Set Default (Optional, Django usually handles this in code, but good for DB) - and Re-add PK
        migrations.RunSQL(
            "ALTER TABLE collection_collection ADD PRIMARY KEY (id);",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # 4.5 Explicitly fix Endpoint FK column (which is still BigInt but needs to be UUID)
        # Since we truncated CASCADE, collection_endpoint is empty.
        migrations.RunSQL(
            "ALTER TABLE collection_endpoint ALTER COLUMN collection_id TYPE uuid USING gen_random_uuid();",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # 5. Tell Django state about the change
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
