# Generated by Django 6.0.1 on 2026-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_alter_collection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('swagger', 'Swagger'), ('postman', 'Postman'), ('crawler', 'Crawler'), ('browser', 'Browser')], default='manual', max_length=20),
        ),
    ]
