# Generated by Django 5.1.15 on 2026-09-05 01:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_alter_collection_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('swagger', 'Swagger'), ('crawler', 'Crawler')], default='swagger', max_length=20)),
                ('source', models.CharField(choices=[('url', 'URL'), ('file', 'File')], default='url', max_length=20)),
                ('spec_name', models.CharField(blank=True, default='', max_length=500)),
                ('spec_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('skip_validation', models.BooleanField(default=False)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='collection.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
