# Generated by Django 5.1.15 on 2026-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='base_url',
            field=models.CharField(blank=True, max_length=500, null=True, help_text='Resolved base_url captured at queue time for URL imports (so the worker and UI don\'t re-derive it from the spec).'),
        ),
    ]
