# Generated by Django 5.1.15 on 2026-09-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_add_base_url_to_importjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='base_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
